"""
engine.snapshot_writer
----------------------
Writes a dated snapshot's output records: summary, manifest, hashes,
folder tree, settings, and ZIP archive.

This module writes ArchiveSnapshot's own records only. It does not
generate Project Context Helper exports — see
engine.project_context_import for that boundary.
"""
from __future__ import annotations

import json
import zipfile
from dataclasses import asdict
from pathlib import Path
from typing import Any

from .app_info import (
    APP_NAME,
    APP_VERSION,
    AUTHOR,
    HASHES_FILENAME,
    MANIFEST_FILENAME,
    REPOSITORY_NAME,
    SETTINGS_FILENAME,
    SUMMARY_FILENAME,
    TREE_FILENAME,
    ZIP_FILENAME,
)
from .settings import ArchiveSettings, ScanResult
from .folder_scanner import build_folder_tree


def human_bytes(value: int) -> str:
    """
    Convert bytes to readable text.
    """

    units = ["B", "KB", "MB", "GB", "TB"]
    amount = float(value)

    for unit in units:
        if amount < 1024 or unit == units[-1]:
            return f"{amount:.2f} {unit}"
        amount /= 1024

    return f"{value} B"


def extension_counts(scan: ScanResult) -> dict[str, int]:
    """
    Count included file extensions.
    """

    counts: dict[str, int] = {}

    for record in scan.included_records:
        counts[record.extension] = counts.get(record.extension, 0) + 1

    return dict(sorted(counts.items()))


def build_manifest(
    root: Path,
    scan: ScanResult,
    settings: ArchiveSettings,
    created: str,
    project_context: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    Build archive manifest dictionary.
    """

    return {
        "created": created,
        "app_name": APP_NAME,
        "app_version": APP_VERSION,
        "author": AUTHOR,
        "repository_name": REPOSITORY_NAME,
        "archive_name": settings.archive_name,
        "archive_description": settings.archive_description,
        "source_root": str(root),
        "settings": settings.to_jsonable(),
        "summary": {
            "included_count": len(scan.included_records),
            "skipped_count": len(scan.skipped_records),
            "included_bytes": scan.total_included_bytes,
            "included_size_readable": human_bytes(scan.total_included_bytes),
            "extension_counts": extension_counts(scan),
        },
        "project_context": project_context or {},
        "included_files": [asdict(record) for record in scan.included_records],
        "skipped_files": [asdict(record) for record in scan.skipped_records],
    }


def build_summary_markdown(
    root: Path,
    scan: ScanResult,
    settings: ArchiveSettings,
    created: str,
    project_context: dict[str, Any] | None = None,
) -> str:
    """
    Build human-readable summary.
    """

    title = settings.archive_name.strip() or root.name
    counts = extension_counts(scan)
    project_context = project_context or {}

    lines: list[str] = []

    lines.append(f"# Archive Snapshot: {title}")
    lines.append("")
    lines.append(f"Generated: `{created}`")
    lines.append(f"Generated by: `{APP_NAME} v{APP_VERSION}`")
    lines.append(f"Author: `{AUTHOR}`")
    lines.append(f"Part of: `{REPOSITORY_NAME}`")
    lines.append("")

    lines.append("## Purpose")
    lines.append("")
    lines.append(
        "This archive snapshot preserves the state and context of a digital "
        "collection at a specific point in time."
    )
    lines.append("")

    lines.append("## Archive Description")
    lines.append("")
    lines.append(settings.archive_description.strip() or "_No archive description provided._")
    lines.append("")

    lines.append("## Source")
    lines.append("")
    lines.append(f"- Source folder: `{root}`")
    lines.append("")

    lines.append("## Snapshot Summary")
    lines.append("")
    lines.append(f"- Included files: `{len(scan.included_records)}`")
    lines.append(f"- Skipped files: `{len(scan.skipped_records)}`")
    lines.append(f"- Included size: `{human_bytes(scan.total_included_bytes)}`")
    lines.append(f"- Hashes generated: `{settings.include_hashes}`")
    lines.append(f"- ZIP snapshot generated: `{settings.include_zip_snapshot}`")
    lines.append("")

    lines.append("## Project Context Helper Bundle")
    lines.append("")
    if project_context:
        lines.append("- Status: `attached`")
        lines.append(f"- Imported files: `{project_context.get('file_count', 0)}`")
        lines.append(f"- Helper version: `{project_context.get('helper_version', '')}`")
        lines.append(f"- Helper profile: `{project_context.get('helper_profile', '')}`")
        helper_created = project_context.get("helper_created", "")
        if helper_created:
            lines.append(f"- Helper export created: `{helper_created}`")
    else:
        lines.append("- Status: `not attached`")
    lines.append("")

    lines.append("## File Types")
    lines.append("")
    if counts:
        for ext, count in counts.items():
            lines.append(f"- `{ext}`: {count}")
    else:
        lines.append("- No included files.")
    lines.append("")

    lines.append("## Preservation Notes")
    lines.append("")
    lines.append(
        "This snapshot is designed so future users can inspect what existed, "
        "how the collection was organized, and whether preserved files remain intact."
    )
    lines.append("")
    lines.append("Generated files may include:")
    lines.append("")
    lines.append(f"- `{SUMMARY_FILENAME}`")
    lines.append(f"- `{MANIFEST_FILENAME}`")
    lines.append(f"- `{HASHES_FILENAME}`")
    lines.append(f"- `{TREE_FILENAME}`")
    lines.append(f"- `{SETTINGS_FILENAME}`")
    lines.append(f"- `{ZIP_FILENAME}`")

    return "\n".join(lines)


def build_hashes_text(scan: ScanResult) -> str:
    """
    Build HASHES.sha256 text.
    """

    lines: list[str] = []

    for record in scan.included_records:
        if record.sha256:
            path = record.relative_path.replace("\\", "/")
            lines.append(f"{record.sha256}  {path}")

    return "\n".join(lines) + ("\n" if lines else "")


def write_snapshot_outputs(
    root: Path,
    export_dir: Path,
    scan: ScanResult,
    settings: ArchiveSettings,
    created: str,
    project_context: dict[str, Any] | None = None,
) -> dict[str, Path | None]:
    """
    Write all generated snapshot files.
    """

    summary_path = export_dir / SUMMARY_FILENAME if settings.include_summary else None
    manifest_path = export_dir / MANIFEST_FILENAME if settings.include_manifest else None
    hashes_path = export_dir / HASHES_FILENAME if settings.include_hashes else None
    tree_path = export_dir / TREE_FILENAME if settings.include_folder_tree else None
    settings_path = export_dir / SETTINGS_FILENAME

    if summary_path:
        summary_path.write_text(
            build_summary_markdown(root, scan, settings, created, project_context),
            encoding="utf-8",
        )

    if manifest_path:
        manifest_path.write_text(
            json.dumps(
                build_manifest(root, scan, settings, created, project_context),
                indent=2,
            ),
            encoding="utf-8",
        )

    if hashes_path:
        hashes_path.write_text(
            build_hashes_text(scan),
            encoding="utf-8",
        )

    if tree_path:
        tree_path.write_text(
            build_folder_tree(root, settings),
            encoding="utf-8",
        )

    settings_path.write_text(
        json.dumps(settings.to_jsonable(), indent=2),
        encoding="utf-8",
    )

    return {
        "summary": summary_path,
        "manifest": manifest_path,
        "hashes": hashes_path,
        "tree": tree_path,
        "settings": settings_path,
    }


def create_zip_snapshot(
    zip_path: Path,
    root: Path,
    scan: ScanResult,
    generated_files: list[Path],
) -> None:
    """
    Create ZIP containing generated records and included files.
    """

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for generated_file in generated_files:
            if generated_file.exists() and generated_file.is_file():
                archive.write(generated_file, generated_file.name)

        for path in scan.included_paths:
            try:
                rel = path.relative_to(root).as_posix()
            except ValueError:
                rel = path.name

            archive.write(path, f"archive_files/{rel}")