"""
tests/test_labels.py

Purpose
-------
Unit tests for `brisartos/labels.py` (`Labels`), the simple label/fixup
resolver used to patch relative-jump targets into generated boot-sector
machine code after the surrounding layout is known. These tests exist
because a fixup-offset bug is exactly the class of error that is invisible
by inspection (the generated bytes still "look like" a valid boot sector)
but produces a boot sector that jumps to the wrong address or fails
`tests/boot_sector_test.py`'s emulator with a hang-forever timeout.

Communication relationships
----------------------------
`Labels` is a standalone helper not currently wired into
`brisartos/boot/make_boot_image.py` (which computes its single far-jump and
two short-jump patches inline via its own `rel8()` function -- see
`tests/test_make_boot_image.py`). `Labels` models the same relative-jump
encoding rule (`target - (source + 1)`, valid range -128..127) that both
`make_boot_image.rel8()` and `tests/boot_sector_test.BootSectorCPU._signed8()`
rely on, so keeping its behavior pinned here protects any future refactor
that consolidates fixup logic into this class.

Settings / parameters
----------------------
- `define(name, offset)`: records the absolute byte offset a label refers
  to. Last write wins if the same name is defined twice.
- `add_fixup(name, source_offset)`: records a byte offset that must be
  overwritten with the correct signed 8-bit relative displacement to
  `name`, once `patch()` runs.
- `patch(image)`: applies every queued fixup against a copy of `image`
  (accepts `bytes` or `bytearray`) and returns a new `bytes` object; the
  input is never mutated in place.

Edge-case behavior
-------------------
- A fixup whose computed relative displacement falls outside -128..127
  must raise `ValueError` naming the offending label, mirroring
  `make_boot_image.rel8()`'s own range check.
- A fixup referencing a label name that was never `define()`-d must raise
  `KeyError` (from the underlying dict lookup) rather than silently
  patching a zero offset.
- `patch()` must not mutate the caller's original `image` argument; it
  copies into a local `bytearray` first and returns fresh `bytes`.
- Multiple independent fixups must each be patched at their own source
  offset without interfering with one another.
"""
import unittest

from _support import add_brisartos_dir_to_syspath

add_brisartos_dir_to_syspath()

from labels import Labels  # noqa: E402


class LabelsTests(unittest.TestCase):
    def test_define_and_single_fixup_in_range(self):
        labels = Labels()
        labels.define("target", 10)
        # A short jump instruction: opcode at offset 5, operand byte at 6.
        # Relative displacement = target - (source_offset + 1) = 10 - 7 = 3
        labels.add_fixup("target", 6)
        image = bytearray(20)
        patched = labels.patch(image)
        self.assertEqual(patched[6], 3)

    def test_patch_returns_bytes_and_does_not_mutate_input(self):
        labels = Labels()
        labels.define("target", 2)
        labels.add_fixup("target", 0)
        original = bytearray(b"\x00\x00\x00\x00")
        patched = labels.patch(original)
        self.assertIsInstance(patched, bytes)
        self.assertEqual(original[0], 0, "original image must not be mutated")
        self.assertEqual(patched[0], 1)  # 2 - (0 + 1) = 1

    def test_negative_relative_displacement(self):
        labels = Labels()
        labels.define("back", 0)
        labels.add_fixup("back", 10)  # displacement = 0 - 11 = -11
        image = bytearray(20)
        patched = labels.patch(image)
        self.assertEqual(patched[10], (-11) & 0xFF)

    def test_boundary_positive_127_is_allowed(self):
        labels = Labels()
        # source_offset=0 -> displacement = target - 1, so target=128 gives +127
        labels.define("far_forward", 128)
        labels.add_fixup("far_forward", 0)
        image = bytearray(200)
        patched = labels.patch(image)
        self.assertEqual(patched[0], 127)

    def test_boundary_negative_128_is_allowed(self):
        # source_offset=200 -> displacement = target - 201, so target=73 gives -128
        labels = Labels()
        labels.define("far_back", 73)
        labels.add_fixup("far_back", 200)
        image = bytearray(300)
        patched = labels.patch(image)
        self.assertEqual(patched[200], (-128) & 0xFF)

    def test_out_of_range_positive_raises_value_error(self):
        labels = Labels()
        labels.define("too_far", 129)
        labels.add_fixup("too_far", 0)  # displacement = 129 - 1 = 128, out of range
        with self.assertRaises(ValueError) as ctx:
            labels.patch(bytearray(200))
        self.assertIn("too_far", str(ctx.exception))

    def test_out_of_range_negative_raises_value_error(self):
        labels = Labels()
        labels.define("too_far_back", 71)
        labels.add_fixup("too_far_back", 200)  # displacement = 71 - 201 = -130
        with self.assertRaises(ValueError):
            labels.patch(bytearray(300))

    def test_undefined_label_raises_key_error(self):
        labels = Labels()
        labels.add_fixup("never_defined", 0)
        with self.assertRaises(KeyError):
            labels.patch(bytearray(10))

    def test_multiple_independent_fixups(self):
        labels = Labels()
        labels.define("a", 5)
        labels.define("b", 15)
        labels.add_fixup("a", 0)   # 5 - 1 = 4
        labels.add_fixup("b", 10)  # 15 - 11 = 4
        image = bytearray(20)
        patched = labels.patch(image)
        self.assertEqual(patched[0], 4)
        self.assertEqual(patched[10], 4)

    def test_redefining_a_label_uses_latest_value(self):
        labels = Labels()
        labels.define("target", 5)
        labels.define("target", 50)  # overwrite
        labels.add_fixup("target", 0)
        patched = labels.patch(bytearray(60))
        self.assertEqual(patched[0], 49)  # 50 - 1


if __name__ == "__main__":
    unittest.main()
