"""
tests/test_make_boot_image.py

Purpose
-------
Unit and integration tests for `brisartos/boot/make_boot_image.py`, the
Python script that hand-assembles BrisartOS's first 512-byte BIOS boot
sector. This is the most safety-sensitive file in the repository: a bug
here does not just fail a test, it produces a boot image whose exact
failure mode ("boots fine in emulation but corrupts memory on real
firmware", per `docs/CHANGELOG.md`'s 0.9.1-alpha entry) is invisible
without behavioral verification. These tests exercise `rel8()` and
`build_boot_sector()` directly as pure functions (no filesystem I/O), and
one integration test feeds the generated bytes through
`tests/boot_sector_test.py`'s own 8086 interpreter end-to-end.

Communication relationships
----------------------------
- `build_boot_sector()` is a pure function: it never touches `OUTPUT` or
  the filesystem itself (only `main()` does), which is exactly what makes
  it safe to unit test without an `IsolatedCwd`/tempdir dance.
- The integration test in this file (`BootSectorEmulatorIntegrationTests`)
  writes `build_boot_sector()`'s output to a `tempfile` and runs it through
  `tests.boot_sector_test.run_boot_image()`, the same emulator entry point
  `python tests/boot_sector_test.py <image>` uses from the command line.
  This is the automated equivalent of the manual verification step
  described in `docs/CHANGELOG.md` for the 0.9.0-alpha and 0.9.1-alpha
  releases ("Re-ran the boot sector emulator against ... both pass").

Settings / parameters
----------------------
- `rel8(source_after_operand, target)`: computes an 8086 short-jump signed
  displacement. Valid range is -128..127 inclusive; anything else must
  raise `ValueError`, mirroring the identical check documented in
  `tests/test_labels.py` for `Labels.patch()`.
- `build_boot_sector()` takes no arguments; every value it produces (stack
  setup, far-jump patch, message offset patch, short-jump patches) is
  derived internally from `BOOT_LOAD_ADDRESS` and `MESSAGE`.

Edge-case behavior
-------------------
- The returned sector must be exactly 512 bytes (`IMAGE_SIZE`) and must end
  with the `0x55 0xAA` BIOS boot signature, or no real or emulated BIOS
  will recognize it as bootable at all.
- `MESSAGE` (BrisartOS's banner text) must appear verbatim, null-terminated,
  somewhere in the generated sector, since the boot code's `mov si, imm16`
  patch point is computed as `BOOT_LOAD_ADDRESS + len(code)` immediately
  before the message bytes are appended -- an off-by-one here would print
  garbage or crash instead of the banner.
- Running the generated sector through the independent 8086 interpreter in
  `tests/boot_sector_test.py` must reach `HLT` (not hang, not raise
  `UnsupportedInstruction`) and must produce BIOS `int 0x10` teletype
  output equal to `MESSAGE` exactly -- this is the strongest behavioral
  guarantee this test suite can offer without real hardware or a real
  emulator such as QEMU or Bochs.
"""
import sys
import tempfile
import unittest
from pathlib import Path

from _support import (
    add_repo_root_to_syspath,
    add_brisartos_boot_to_syspath,
    load_module_from_path,
)

add_repo_root_to_syspath()
add_brisartos_boot_to_syspath()

import make_boot_image  # noqa: E402

# Loaded by explicit file path under a private alias rather than
# `from tests import boot_sector_test`, because some Python environments
# have an unrelated, site-installed package literally named `tests` that
# would otherwise shadow this repository's tests/ directory -- see
# tests/_support.py's docstring for the full rationale.
boot_sector_test = load_module_from_path(
    "brisartos_boot_sector_test_module", "tests/boot_sector_test.py"
)


class Rel8Tests(unittest.TestCase):
    def test_zero_displacement(self):
        self.assertEqual(make_boot_image.rel8(10, 10), 0)

    def test_positive_displacement(self):
        self.assertEqual(make_boot_image.rel8(10, 15), 5)

    def test_negative_displacement_two_complement_encoding(self):
        self.assertEqual(make_boot_image.rel8(10, 5), (-5) & 0xFF)

    def test_boundary_127_is_allowed(self):
        self.assertEqual(make_boot_image.rel8(0, 127), 127)

    def test_boundary_negative_128_is_allowed(self):
        self.assertEqual(make_boot_image.rel8(0, -128), 0x80)

    def test_128_raises_value_error(self):
        with self.assertRaises(ValueError):
            make_boot_image.rel8(0, 128)

    def test_negative_129_raises_value_error(self):
        with self.assertRaises(ValueError):
            make_boot_image.rel8(0, -129)


class BuildBootSectorTests(unittest.TestCase):
    def setUp(self):
        self.sector = make_boot_image.build_boot_sector()

    def test_sector_is_exactly_512_bytes(self):
        self.assertEqual(len(self.sector), make_boot_image.IMAGE_SIZE)

    def test_sector_ends_with_boot_signature(self):
        self.assertEqual(self.sector[-2:], make_boot_image.SIGNATURE)

    def test_sector_is_deterministic_across_calls(self):
        second_build = make_boot_image.build_boot_sector()
        self.assertEqual(self.sector, second_build)

    def test_message_bytes_present_and_null_terminated(self):
        expected = make_boot_image.MESSAGE.encode("ascii") + b"\x00"
        self.assertIn(expected, self.sector)

    def test_sector_is_returned_as_bytes(self):
        self.assertIsInstance(self.sector, bytes)

    def test_padding_between_code_and_signature_is_zero_filled(self):
        # Anything that is not the leading code+message and not the final
        # 2-byte signature must be zero padding.
        message_with_terminator = make_boot_image.MESSAGE.encode("ascii") + b"\x00"
        message_start = self.sector.index(message_with_terminator)
        message_end = message_start + len(message_with_terminator)
        padding = self.sector[message_end:-2]
        self.assertEqual(padding, b"\x00" * len(padding))


class BootSectorEmulatorIntegrationTests(unittest.TestCase):
    """
    End-to-end check: build a real boot sector with make_boot_image, then
    execute it with the independent 8086 interpreter in
    tests/boot_sector_test.py, exactly as `python tests/boot_sector_test.py
    <image>` does from the command line.
    """

    def test_generated_sector_boots_and_prints_banner_via_emulator(self):
        sector = make_boot_image.build_boot_sector()
        with tempfile.TemporaryDirectory() as tmp_dir:
            image_path = Path(tmp_dir) / "brisartos_boot.img"
            image_path.write_bytes(sector)
            output = boot_sector_test.run_boot_image(image_path)
        self.assertEqual(output, make_boot_image.MESSAGE)

    def test_truncated_image_is_rejected_by_the_loader(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            image_path = Path(tmp_dir) / "too_short.img"
            image_path.write_bytes(b"\x00" * 100)
            with self.assertRaises(ValueError):
                boot_sector_test.run_boot_image(image_path)

    def test_missing_signature_is_rejected_by_the_loader(self):
        sector = bytearray(make_boot_image.build_boot_sector())
        sector[-2:] = b"\x00\x00"  # corrupt the 55AA signature
        with tempfile.TemporaryDirectory() as tmp_dir:
            image_path = Path(tmp_dir) / "bad_signature.img"
            image_path.write_bytes(bytes(sector))
            with self.assertRaises(ValueError):
                boot_sector_test.run_boot_image(image_path)


if __name__ == "__main__":
    unittest.main()
