"""
Markdown and manifest generators for ReleaseNoteBuilder.
"""

from __future__ import annotations

import json
from pathlib import Path
from constants import (
    APP_NAME,
    APP_VERSION,
    AUTHOR,
    REPOSITORY_NAME,
    REPOSITORY_URL,
    OUTPUT_RELEASE_NOTES,
    OUTPUT_CHANGELOG,
    OUTPUT_MANIFEST,
)
from filesystem import timestamp_now
from classifiers import classify_release_changes, summarize_release_type


def bullet_lines(items: list[str]) -> str:
    if not items:
        return "- No notable entries detected."
    return "\n".join(f"- {item}" for item in items)


def file_bullet_lines(items: list[dict], key: str = "path") -> str:
    if not items:
        return "- No files detected."
    return "\n".join(f"- `{item.get(key, '')}`" for item in items)


def modified_file_bullet_lines(items: list[dict]) -> str:
    if not items:
        return "- No files detected."
    return "\n".join(f"- `{item.get('path', '')}`" for item in items)


def build_release_notes_markdown(comparison: dict, version_label: str = "Unversioned Release") -> str:
    diff = comparison["diff"]
    classified = classify_release_changes(diff)
    release_type = summarize_release_type(classified, diff)
    added_count = len(diff.get("added", []))
    modified_count = len(diff.get("modified", []))
    removed_count = len(diff.get("removed", []))
    unchanged_count = len(diff.get("unchanged", []))

    return f"""# Release Notes

## {version_label}

Generated: {timestamp_now()}  
Generated by: {APP_NAME} v{APP_VERSION}  
Author: {AUTHOR}  
Repository: {REPOSITORY_NAME}  
Repository URL: {REPOSITORY_URL}

---

## Release Summary

{release_type}

This release note draft was generated by comparing an older project folder against a newer project folder.

---

## Added

{bullet_lines(classified["added"])}

---

## Changed

{bullet_lines(classified["changed"])}

---

## Removed

{bullet_lines(classified["removed"])}

---

## File Change Statistics

- Files added: {added_count}
- Files modified: {modified_count}
- Files removed: {removed_count}
- Files unchanged: {unchanged_count}
- Old project file count: {comparison["old_file_count"]}
- New project file count: {comparison["new_file_count"]}

---

## Changed Files

### Added Files

{file_bullet_lines(diff.get("added", []))}

### Modified Files

{modified_file_bullet_lines(diff.get("modified", []))}

### Removed Files

{file_bullet_lines(diff.get("removed", []))}

---

## Notes

These release notes were generated automatically by comparing project snapshots.

Review and edit this file before publishing if you want a more human-polished release announcement.
"""


def build_changelog_markdown(comparison: dict, version_label: str = "Unversioned Release") -> str:
    diff = comparison["diff"]
    classified = classify_release_changes(diff)

    return f"""# Changelog Draft

## {version_label}

### Added

{bullet_lines(classified["added"])}

### Changed

{bullet_lines(classified["changed"])}

### Removed

{bullet_lines(classified["removed"])}

---

Generated by {APP_NAME} v{APP_VERSION}.
"""


def build_manifest(comparison: dict, version_label: str = "Unversioned Release") -> dict:
    diff = comparison["diff"]
    classified = classify_release_changes(diff)
    release_type = summarize_release_type(classified, diff)

    return {
        "created": timestamp_now(),
        "app_name": APP_NAME,
        "version": APP_VERSION,
        "author": AUTHOR,
        "repository_name": REPOSITORY_NAME,
        "repository_url": REPOSITORY_URL,
        "release_label": version_label,
        "release_type": release_type,
        "old_root": comparison["old_root"],
        "new_root": comparison["new_root"],
        "old_file_count": comparison["old_file_count"],
        "new_file_count": comparison["new_file_count"],
        "statistics": {
            "files_added": len(diff.get("added", [])),
            "files_modified": len(diff.get("modified", [])),
            "files_removed": len(diff.get("removed", [])),
            "files_unchanged": len(diff.get("unchanged", [])),
        },
        "classified_changes": classified,
        "files": {
            "added": [item["path"] for item in diff.get("added", [])],
            "modified": [item["path"] for item in diff.get("modified", [])],
            "removed": [item["path"] for item in diff.get("removed", [])],
            "unchanged": [item["path"] for item in diff.get("unchanged", [])],
        },
    }


def write_outputs(output_folder: Path, comparison: dict, version_label: str = "Unversioned Release") -> dict:
    output_folder.mkdir(parents=True, exist_ok=True)
    release_notes_path = output_folder / OUTPUT_RELEASE_NOTES
    changelog_path = output_folder / OUTPUT_CHANGELOG
    manifest_path = output_folder / OUTPUT_MANIFEST

    release_notes = build_release_notes_markdown(comparison, version_label)
    changelog = build_changelog_markdown(comparison, version_label)
    manifest = build_manifest(comparison, version_label)

    release_notes_path.write_text(release_notes, encoding="utf-8")
    changelog_path.write_text(changelog, encoding="utf-8")
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    return {
        "release_notes": str(release_notes_path),
        "changelog": str(changelog_path),
        "manifest": str(manifest_path),
    }
