"""
Output generators for AutoExeBuilder.
"""

from __future__ import annotations

import json
from pathlib import Path

from build_profiles import BuildProfile
from constants import (
    APP_NAME,
    APP_VERSION,
    AUTHOR,
    BUILD_COMMAND_FILENAME,
    BUILD_MANIFEST_FILENAME,
    BUILD_NOTES_FILENAME,
    REPOSITORY_NAME,
    REPOSITORY_URL,
)
from filesystem import timestamp_now
from pyinstaller_backend import expected_executable_path


def write_build_outputs(
    profile: BuildProfile,
    scan: dict,
    build_result: dict,
) -> dict:
    """
    Write build command, notes, and manifest files.
    """
    output_root = Path(profile.output_folder).expanduser().resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    created = timestamp_now()

    command_path = output_root / BUILD_COMMAND_FILENAME
    notes_path = output_root / BUILD_NOTES_FILENAME
    manifest_path = output_root / BUILD_MANIFEST_FILENAME

    command_text = build_result.get("command", "")

    command_path.write_text(command_text + "\n", encoding="utf-8")

    notes = build_notes_markdown(
        profile=profile,
        scan=scan,
        build_result=build_result,
        created=created,
    )
    notes_path.write_text(notes, encoding="utf-8")

    manifest = build_manifest(
        profile=profile,
        scan=scan,
        build_result=build_result,
        created=created,
    )
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    return {
        "command": str(command_path),
        "notes": str(notes_path),
        "manifest": str(manifest_path),
        "expected_executable": expected_executable_path(profile),
    }


def build_manifest(
    profile: BuildProfile,
    scan: dict,
    build_result: dict,
    created: str,
) -> dict:
    """
    Build machine-readable build metadata.
    """
    return {
        "created": created,
        "app_name": APP_NAME,
        "app_version": APP_VERSION,
        "author": AUTHOR,
        "repository_name": REPOSITORY_NAME,
        "repository_url": REPOSITORY_URL,
        "build_profile": profile.to_dict(),
        "scan": scan,
        "build_result": {
            "success": build_result.get("success"),
            "return_code": build_result.get("return_code"),
            "command": build_result.get("command"),
            "stderr_preview": build_result.get("stderr", "")[:4000],
            "stdout_preview": build_result.get("stdout", "")[:4000],
        },
        "expected_executable": expected_executable_path(profile),
    }


def build_notes_markdown(
    profile: BuildProfile,
    scan: dict,
    build_result: dict,
    created: str,
) -> str:
    """
    Build human-readable build notes.
    """
    status = "Success" if build_result.get("success") else "Failed"

    lines: list[str] = []

    lines.append(f"# {profile.executable_name} EXE Build Notes\n\n")
    lines.append(f"Generated: `{created}`\n\n")
    lines.append(f"Generated by: `{APP_NAME} v{APP_VERSION}`\n\n")
    lines.append(f"Author: `{AUTHOR}`\n\n")
    lines.append(f"Repository: `{REPOSITORY_NAME}`\n\n")
    lines.append(f"Repository URL: `{REPOSITORY_URL}`\n\n")

    lines.append("## Build Status\n\n")
    lines.append(f"- Status: `{status}`\n")
    lines.append(f"- Return code: `{build_result.get('return_code')}`\n")
    lines.append(f"- Expected executable: `{expected_executable_path(profile)}`\n\n")

    lines.append("## Build Profile\n\n")
    lines.append(f"- Project root: `{profile.project_root}`\n")
    lines.append(f"- Entry point: `{profile.entrypoint}`\n")
    lines.append(f"- Output folder: `{profile.output_folder}`\n")
    lines.append(f"- Executable name: `{profile.executable_name}`\n")
    lines.append(f"- Bundle mode: `{'onefile' if profile.onefile else 'onedir'}`\n")
    lines.append(f"- Window mode: `{'windowed' if profile.windowed else 'console'}`\n")
    lines.append(f"- Clean build: `{profile.clean_build}`\n")
    lines.append(f"- Icon path: `{profile.icon_path if profile.icon_path else 'none'}`\n\n")

    lines.append("## Command Used\n\n")
    lines.append("```bash\n")
    lines.append(build_result.get("command", ""))
    lines.append("\n```\n\n")

    lines.append("## Project Scan Summary\n\n")
    lines.append(f"- Files scanned: `{scan.get('files_scanned')}`\n")
    lines.append(f"- Python files scanned: `{scan.get('python_files_scanned')}`\n")
    lines.append(f"- Suggested entry point: `{scan.get('suggested_entrypoint')}`\n")
    lines.append(f"- Uses Tkinter: `{scan.get('uses_tkinter')}`\n")
    lines.append(f"- Possible external imports: `{', '.join(scan.get('possible_external_imports', [])) or 'none detected'}`\n\n")

    if not build_result.get("success"):
        lines.append("## Error Output\n\n")
        lines.append("```text\n")
        lines.append(build_result.get("stderr", ""))
        lines.append("\n```\n\n")

    lines.append("## Notes\n\n")
    lines.append(
        "- AutoExeBuilder itself is a standard-library Python utility.\n"
        "- Executable packaging requires PyInstaller to be installed in the active Python environment.\n"
        "- Review the generated executable before distribution.\n"
        "- Newly built unsigned executables may trigger Windows SmartScreen or antivirus warnings.\n"
    )

    return "".join(lines)